spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moretech-db
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true

2gis:
  api:
    url: "https://catalog.api.2gis.com/3.0/items"
    key: "3ace0e09-9316-4ece-9861-08ea7c96e5b5"
